apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: acm-lab-deploy
  source:
    path: sealed-secrets-operator/base
    repoURL: https://github.com/redhat-cop/gitops-catalog
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  sync:
    comparedTo:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      source:
        path: sealed-secrets-operator/base
        repoURL: https://github.com/redhat-cop/gitops-catalog
        targetRevision: main
