apiVersion: v1
kind: Event
metadata:
  namespace: openshift-gatekeeper-system
  annotations:
    constraint_action: deny
    constraint_kind: K8sRequiredLabels
    constraint_name: ns-must-have-gk
    event_type: violation
