apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acm-lab-deploy
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
