apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerImageLatest
metadata:
  name: containerimagelatest-obj
spec:
  match:
    kinds:
      - apiGroups:
          - apps.openshift.io
          - apps
        kinds:
          - DeploymentConfig
          - DaemonSet
          - Deployment
          - StatefulSet
