apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-opa
  name: test-opa-nok
spec:
  containers:
  - image: quay.io/rcarrata/in-cluster:0.9.1
    name: test-opa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
