apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-opa
  name: test-opa-ok
spec:
  containers:
  - image: quay.io/rcarrata/in-cluster:0.9.1
    name: test-opa
    resources: {}
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
